JobsBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: JobsBundle:Default:index }
    
JobsBundle_job:
    resource: "@JobsBundle/Resources/config/routing/job.yml"
    prefix:   /job
