parameters:
#    jobs.example.class: WSAD\JobsBundle\Example

services:
#    jobs.example:
#        class: %jobs.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
     jobs.twig.extension:
        class: WSAD\JobsBundle\Extension\JobsExtension
        tags:
            - { name: twig.extension }
