<?php

namespace WSAD\JobsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getContainingJobs()
	{
		$dql = 'SELECT c FROM '.$this->_entityName.' c LEFT JOIN c.jobs j '
			  .'WHERE j.expires_at > ?1 AND j.is_activated = ?2';
		
	    $query = $this->_em->createQuery($dql);
	    $query->setParameters(array(1 => new \DateTime, 2 => true));
	    
    	return $query->getResult();					
	}
	
	public function getCategoriesWithJobs($limit)
	{
		$categories = $this->getContainingJobs();
		$jobsRepository = $this->_em->getRepository('JobsBundle:Job');
		
		foreach($categories as $c) {
			$c->setActiveJobs($jobsRepository->getJobsByCategory($c->getId(), $limit));
		}
		
		return $categories;
	}
}