<?php

namespace WSAD\JobsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{	
	public function getActiveByCategory($cid, $limit) 
	{
		$dql = 'SELECT j FROM '.$this->_entityName.' j WHERE j.category = ?1 ' 
			  .'AND j.is_activated = ?2 AND j.expires_at > ?3 ORDER BY j.expires_at DESC';
		
		$query = $this->_em->createQuery($dql);
		$query->setParameters(array(1 => $cid, 2 => true, 3 => new \DateTime));
		$query->setMaxResults($limit);
		
		return $query->getResult();
	}
}